language: java
before_deploy:
  - export TARGET=$(ls target/SafeStaff-*.jar)
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  skip_cleanup: true
  file: "${TARGET}"
  on:
    tags: true
  overwrite: true