name: SafeStaff
author: bmlzootown
version: 1.5
main: ml.bmlzootown.SafeStaff
api-version: 1.13
commands:
     safestaff:
          description: Displays available commands for SafeStaff
     login:
          description: Allows a staff member to login
permissions:
    SafeStaff.use:
        default: false
    SafeStaff.admin:
        default: false
    SafeStaff.mod:
        default: false
    SafeStaff.notification:
        default: op